export const teamMembers = [
  {
    name: 'Blymm',
    title: `Creator and executive producer of The Irregulars Sports Show`,
    photoSrc: '/profile-blymm.png',
    teams: `Teams Placeholder`,
    bio: 'Formerly of the hip hop group Rainwater Conglomerate, one half of the duo Baby C & Blymm',
    quote: `We are making sports cool again!`,
  },
  {
    name: 'Coach',
    title: 'Former Head Coach for Kamiak J.V. Football',
    photoSrc: '/profile-coach.jpeg',
    teams:
      'Seattle Seahawks, San Francisco Giants, and any University of Tulsa Golden Hurricane team',
    bio: 'Raising two sons and proud of it!',
    quote: `If it isn't fun, then what's the point?`,
  },
  {
    name: 'Luke 3:16',
    title: '',
    photoSrc: '/profile-luke316.jpeg',
    teams:
      'Kansas City Chiefs, Seattle Mariners, Seattle Supersonics, Oklahoma State University',
    bio: 'WESCO South Assistant Wrestling Coach of the Year  in 2008, Former Head Coach of the Kamiak High School J.V. Football team',
    quote: `Placeholder quote.`,
  },
  {
    name: 'ZeeFeezee',
    title: ``,
    photoSrc: '/profile-ZeeFeezee.jpeg',
    teams: `Chicago Bears, Chicago White Sox, SeattleSeahawks`,
    bio: 'Placeholder bio.',
    quote: `Do dope shit, with dope people!`,
  },
  {
    name: 'Ratt Pack Attack Alex',
    title: ``,
    photoSrc: '/profile-alex.jpeg',
    teams: `Bulls , Jayhawks , Penn State (NCAAF) , Eagles (NFL) `,
    bio: '2022 Irregulars March Madness bracket champion.',
    quote: `I had a purpose before anyone had an opinion.`,
  },
  {
    name: 'Vanni The God',
    title: ``,
    photoSrc: '/profile-vanni.jpeg',
    teams: `Seattle Seahawks , Mariners, Lakers`,
    bio: 'Former D1 rugby player.',
    quote: `Let's Do It Now & Not Later !`,
  },
  {
    name: 'Facemob',
    title: ``,
    photoSrc: '/profile-facemob.jpeg',
    teams: `Las Vegas Raiders, Utah Jazz, NY Yankees`,
    bio: 'Greatest achievement is overcoming the lies of this world and trusting in God’s plan of salvation.',
    quote: `Endure until the end`,
  },
  {
    name: 'Just Alex',
    title: `Just Alex`,
    photoSrc: '/profile-just-alex.jpeg',
    teams: `Possibly the whole Eastern Seaboard, whoever is playing well!?!?!?!?`,
    bio: `Master's Degree in Special Education, Girls Flag Football Head Coach, Comedian!`,
    quote: ``,
  },
  {
    name: 'codeMonkeyHopeful',
    title: 'Head Dev in Charge (yup HDIC)',
    photoSrc: '/profile-ryan.jpg',
    teams: 'The fuck is a team? Ohhh, ohh, sports, go team!',
    bio: 'Built this site and love the crew! Grew up in Ohio, went to OSU, married a wolverine... Love all things tech!',
    quote:
      'There are only two mistakes one can make along the road to truth; not going all the way, and not starting.',
  },
];
